---@meta

---@class FAnimBlueprintGeneratedConstantData : FAnimBlueprintConstantData
---@field __NameProperty_2374 FName
---@field __NameProperty_2375 FName
---@field __ArrayProperty_2376 TArray<float>
---@field __ArrayProperty_2377 TArray<int32>
---@field __ArrayProperty_2378 TArray<float>
---@field __ArrayProperty_2379 TArray<float>
---@field __ArrayProperty_2380 TArray<int32>
---@field __NameProperty_2381 FName
---@field __FloatProperty_2382 float
---@field __ArrayProperty_2383 TArray<int32>
---@field __NameProperty_2384 FName
---@field __NameProperty_2385 FName
---@field __NameProperty_2386 FName
---@field __NameProperty_2387 FName
---@field __NameProperty_2388 FName
---@field __NameProperty_2389 FName
---@field __NameProperty_2390 FName
---@field __NameProperty_2391 FName
---@field __NameProperty_2392 FName
---@field __NameProperty_2393 FName
---@field __NameProperty_2394 FName
---@field __FloatProperty_2395 float
---@field __ByteProperty_2396 EAnimGroupRole::Type
---@field __NameProperty_2397 FName
---@field __NameProperty_2398 FName
---@field __FloatProperty_2399 float
---@field __NameProperty_2400 FName
---@field __NameProperty_2401 FName
---@field __NameProperty_2402 FName
---@field __IntProperty_2403 int32
---@field __NameProperty_2404 FName
---@field __IntProperty_2405 int32
---@field __NameProperty_2406 FName
---@field __IntProperty_2407 int32
---@field __NameProperty_2408 FName
---@field __IntProperty_2409 int32
---@field __NameProperty_2410 FName
---@field __IntProperty_2411 int32
---@field __NameProperty_2412 FName
---@field __NameProperty_2413 FName
---@field __NameProperty_2414 FName
---@field __NameProperty_2415 FName
---@field __NameProperty_2416 FName
---@field __ArrayProperty_2417 TArray<int32>
---@field __ArrayProperty_2418 TArray<float>
---@field __ArrayProperty_2419 TArray<int32>
---@field __ArrayProperty_2420 TArray<int32>
---@field __NameProperty_2421 FName
---@field __EnumProperty_2422 EAnimSyncMethod
---@field __NameProperty_2423 FName
---@field __BoolProperty_2424 boolean
---@field __ArrayProperty_2425 TArray<float>
---@field __NameProperty_2426 FName
---@field __IntProperty_2427 int32
---@field __FloatProperty_2428 float
---@field __StructProperty_2429 FInputScaleBiasClampConstants
---@field __FloatProperty_2430 float
---@field __EnumProperty_2431 EAnimSyncMethod
---@field __ByteProperty_2432 EAnimGroupRole::Type
---@field __BlendProfile_2433 UBlendProfile
---@field __CurveFloat_2434 UCurveFloat
---@field __BoolProperty_2435 boolean
---@field __EnumProperty_2436 EAlphaBlendOption
---@field __EnumProperty_2437 EBlendListTransitionType
---@field __ArrayProperty_2438 TArray<float>
---@field __NameProperty_2439 FName
---@field __NameProperty_2440 FName
---@field __IntProperty_2441 int32
---@field __StructProperty_2442 FAnimNodeFunctionRef
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystem_PropertyAccess
---@field AnimBlueprintExtension_Base FAnimSubsystem_Base
FAnimBlueprintGeneratedConstantData = {}



---@class FAnimBlueprintGeneratedMutableData : FAnimBlueprintMutableData
---@field __FloatProperty float
---@field __FloatProperty_0 float
---@field __ByteProperty_1 uint8
---@field __BoolProperty_2 boolean
---@field __BoolProperty_3 boolean
---@field __FloatProperty_4 float
---@field __FloatProperty_5 float
---@field __FloatProperty_6 float
---@field __ByteProperty_7 uint8
---@field __BoolProperty_8 boolean
---@field __ByteProperty_9 uint8
---@field __BoolProperty_10 boolean
---@field __FloatProperty_11 float
---@field __FloatProperty_12 float
---@field __FloatProperty_13 float
---@field __ByteProperty_14 uint8
---@field __FloatProperty_15 float
---@field __FloatProperty_16 float
---@field __BoolProperty_17 boolean
---@field __FloatProperty_18 float
---@field __FloatProperty_19 float
---@field __FloatProperty_20 float
---@field __FloatProperty_21 float
---@field __FloatProperty_22 float
---@field __FloatProperty_23 float
---@field __FloatProperty_24 float
---@field __FloatProperty_25 float
---@field __FloatProperty_26 float
---@field __FloatProperty_27 float
---@field __FloatProperty_28 float
---@field __FloatProperty_29 float
---@field __BoolProperty_30 boolean
---@field __FloatProperty_31 float
---@field __FloatProperty_32 float
---@field __FloatProperty_33 float
---@field __FloatProperty_34 float
---@field __FloatProperty_35 float
---@field __BoolProperty_36 boolean
---@field __BoolProperty_37 boolean
---@field __BoolProperty_38 boolean
---@field __ByteProperty_39 uint8
---@field __BoolProperty_40 boolean
---@field __FloatProperty_41 float
---@field __ByteProperty_42 uint8
---@field __ByteProperty_43 uint8
---@field __BoolProperty_44 boolean
---@field __BoolProperty_45 boolean
---@field __BoolProperty_46 boolean
---@field __BoolProperty_47 boolean
---@field __BoolProperty_48 boolean
---@field __BoolProperty_49 boolean
---@field __BoolProperty_50 boolean
---@field __BoolProperty_51 boolean
---@field __BoolProperty_52 boolean
---@field __FloatProperty_53 float
---@field __BoolProperty_54 boolean
---@field __BoolProperty_55 boolean
---@field __BoolProperty_56 boolean
---@field __BoolProperty_57 boolean
---@field __BoolProperty_58 boolean
FAnimBlueprintGeneratedMutableData = {}



---@class UABP_PrototypeChar_C : UVisPlayerAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field __AnimBlueprintMutables FAnimBlueprintGeneratedMutableData
---@field AnimBlueprintExtension_PropertyAccess FAnimSubsystemInstance
---@field AnimBlueprintExtension_Base FAnimSubsystemInstance
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_Slot_4 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_8 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_92 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_91 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_82 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_68 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_81 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_67 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_24 FAnimNode_StateMachine
---@field AnimGraphNode_LayeredBoneBlend_7 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByEnum_6 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_80 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_23 FAnimNode_BlendListByBool
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_90 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_89 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_79 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_66 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_78 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_22 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_15 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_65 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_23 FAnimNode_StateMachine
---@field AnimGraphNode_SequencePlayer_77 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_76 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_75 FAnimNode_SequencePlayer
---@field AnimGraphNode_TransitionResult_88 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_87 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_74 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_64 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_73 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_63 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_22 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByEnum_5 FAnimNode_BlendListByEnum
---@field AnimGraphNode_LayeredBoneBlend_6 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TransitionResult_86 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_85 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_84 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_83 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_82 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_81 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_80 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_79 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_72 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_62 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_71 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_61 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_70 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_60 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_69 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_59 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_21 FAnimNode_StateMachine
---@field AnimGraphNode_SequencePlayer_68 FAnimNode_SequencePlayer
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_78 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_77 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_67 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_58 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_66 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_21 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_57 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_20 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_76 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_75 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_65 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_64 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_4 FAnimNode_BlendListByEnum
---@field AnimGraphNode_StateResult_56 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_63 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_20 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_14 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_55 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_19 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_74 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_73 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_62 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_54 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_13 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_53 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_18 FAnimNode_StateMachine
---@field AnimGraphNode_LayeredBoneBlend_5 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TransitionResult_72 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_71 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_61 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_52 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_12 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_51 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_17 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByEnum_3 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_60 FAnimNode_SequencePlayer
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_70 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_69 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_59 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_50 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_11 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_19 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_10 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_49 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_16 FAnimNode_StateMachine
---@field AnimGraphNode_SequencePlayer_58 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendSpacePlayer_9 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_8 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_57 FAnimNode_SequencePlayer
---@field AnimGraphNode_TransitionResult_68 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_67 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_56 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_48 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_7 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_47 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_15 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_66 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_65 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_64 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_63 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_62 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_61 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_60 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_59 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_58 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_57 FAnimNode_TransitionResult
---@field AnimGraphNode_StateResult_46 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_55 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_45 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_54 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_44 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_53 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_43 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_52 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_42 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_56 FAnimNode_TransitionResult
---@field AnimGraphNode_StateResult_41 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_14 FAnimNode_StateMachine
---@field AnimGraphNode_ApplyMeshSpaceAdditive FAnimNode_ApplyMeshSpaceAdditive
---@field AnimGraphNode_LayeredBoneBlend_4 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TransitionResult_55 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_54 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_53 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_52 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_51 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_50 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_49 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_48 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_51 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_40 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_50 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_39 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_49 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_38 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_48 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_37 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_47 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_36 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_13 FAnimNode_StateMachine
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_47 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_46 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_45 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_44 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_43 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_42 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_41 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_40 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_46 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_35 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_45 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_34 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_44 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_33 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_43 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_32 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_42 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_31 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_12 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_39 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_38 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_37 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_36 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_35 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_41 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_30 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_40 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_29 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_39 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_28 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_11 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_34 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_33 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_38 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_27 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_37 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_26 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_36 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_25 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_35 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_24 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_34 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_23 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_6 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_22 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_5 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_21 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_20 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_33 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_18 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_32 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_19 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_10 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_9 FAnimNode_StateMachine
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_BlendListByBool_17 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_31 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_30 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_8 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_16 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_29 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_15 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_28 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_27 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_2 FAnimNode_BlendListByEnum
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_26 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_14 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_7 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByEnum_1 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_25 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_24 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_23 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByBool_13 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_22 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_21 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_12 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_20 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_19 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_11 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_6 FAnimNode_StateMachine
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_10 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_18 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_17 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_16 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_9 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_5 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_8 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_7 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field UpperBodySpeedReference double
---@field deltaT double
---@field PulseSumTime double
---@field staticYaw double
---@field deltaYaw double
---@field shouldTurnLeft boolean
---@field shouldTurnRight boolean
---@field staticYaw_Rotator FRotator
UABP_PrototypeChar_C = {}

---@param AnimGraph FPoseLink
function UABP_PrototypeChar_C:AnimGraph(AnimGraph) end
---@param delta_Time_X double
---@param interval__seconds_ double
---@param Fire boolean
function UABP_PrototypeChar_C:PulseTimer(delta_Time_X, interval__seconds_, Fire) end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_SequencePlayer_2C58BF374F7F8C8D168D968559D1C73E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_SequencePlayer_8338F95C4AF3E60124916B8D9A86FABA() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_686AB5B9467388087C4A93AD751E2DB8() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_C815C8BD46E6A68D87842CB13965B418() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_1853F427406B8696E0DD9B9126CD8ACA() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_6AE9A11E4AC7CB76D59717AC5854974F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_3D2F2855431BE7A9BF65EF981D79F5ED() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9C9ABEBD4BB6914F30F933B941322A37() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_8C49E44749D3C8D87655CF81BA3D48AC() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_3885F79B436D8BBA1EEC1982DE83D238() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_5E0FD4E8424EEC6E47BC1BBC39122F4B() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_780D3CFB41672203FAC93CB747A2E36B() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_LayeredBoneBlend_43B06F934FBE1EA068BE73B82C2DE8EB() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_RotationOffsetBlendSpace_5E125D6741B69877F4BEACA5446DA1CC() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendSpacePlayer_A93DB38D49738EF832DCF492B403C3DF() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_SequencePlayer_924A231840EFD8BFAEE6FF97D5A9DF8F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_SequencePlayer_A207C5FD40B4BD992FDDAB8681219062() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_SequencePlayer_98973D2647D559DC03C63CA996985C30() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TwoWayBlend_354DD17E4A0C899E8EF85C97E420B17E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendListByBool_FBFF0D7845C1F627350B45A6D3DA09F8() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_3B44311A42BB062F6395A78215545FB2() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendListByBool_6FA0E5C74228C147FFCA35912B4A8E37() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendListByBool_AFFD83294BBF6EA2FB249A82BF315318() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendSpacePlayer_569182384AB455A21DB9238AEEDBB1FB() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendSpacePlayer_52E62E8143CB17BDC6A08EB5493027CF() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendSpacePlayer_EEC0EE6B453CDE2209A34C9C3B99A1EC() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_BlendSpacePlayer_978DE16C46A78FFD9CDC00889AFD239F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_DF5884634813232EC67CBAB48D82B22E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_710D5A214ECC75C3D7D00E800AEF03AF() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_8777FE7A40FCA52A1C317E94399A2D66() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_46D65A244EF23A79ABE361A567E8D58B() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_D2B657A041ADC611BBF968891818A99D() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_695178C1429EA507C2165D9D92E9B834() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_ACD3E5654F41C39EE3DFAB865A1AC99E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9E6836A8488B7A1E8ACB1D9FA7A72757() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_353AF253486D7630AB97F88B07C5661F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9E9000A84F50CD6F2596D89C6296AFC1() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_0AF50E0F40D646C553051784B1A2FDE6() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9E85687A4D42A0332DDFA5A1764DF68F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_4758618B43A04D2B378C67A93228D660() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_D663FA854A89036CAF515297692B8492() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_2D3431EC4844A7874E7CD0BD32598D3D() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_3E068B5642D200DB3AA63B95548D38E7() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_3A59D3D341EC37A529B0768AC7B8CE7E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_4D69EF0442547F9C343F639B1F4A9ED2() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_24180EF446A84163D83F6197D84A06DC() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9F86F4274C887804665E6D85F21BE8B9() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_CF88AE814CF17892C634339AB14C7797() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_EA4E5C2E42B91FFD3031EEA09DCE450E() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_CB1EAFFA47CB7178B1A91B9B589A5083() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_701244454584CF5DE13C578EEE1821F3() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_E4AD2EA74C12051E3EAC0C9D39B6A19F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_B9694DF24E3A369B6EEA518CF75BA22A() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_2305E5AB4A9F915BFA0A85992A818339() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_A7E0250749BF12390A6633935A4AA1DA() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_63ED07374E0841AE4224E0911797824F() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_43D9D526462A3EA35E1C5EB9132375DE() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9523468E48F6D4B6862B4DAB95DD5EA4() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_0042A5F2498D273BCDBF2C95607451CB() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_294A0D67453E62ADBF0F9CA3FDF6C24C() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_FEC2C9A44587124ADC26EEB4DD9D4A32() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_F34D8988471C7BB266A71D9B3C053C52() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_108E382A4509A3FEAC848AA665CA2628() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9CF9E80F4DD4CD385EC47EA36CE693A6() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_B1420EF04C8C71DF451583A87D9A2EE5() end
---@param DeltaTimeX float
function UABP_PrototypeChar_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_983AD3B343DCE6D65397ABB292BD2AD1() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_26FFE99A48A804F389B8D997EBD7C04A() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_C9D9300F4A5CBCD633ABCD97442C5790() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_9770F3F04C359B18323B6FB66194DC31() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_6A95239F42694D5DFD67CA96F0769457() end
function UABP_PrototypeChar_C:AnimNotify_reset_turnRvar() end
function UABP_PrototypeChar_C:AnimNotify_reset_turnLvar() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_69ACDD034E3DED8E404C72814D06B7D3() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_4D1773E34EA33CB4FFF59DAB5B43EB51() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_A86A6A2A4053129BAFC27D981827D775() end
function UABP_PrototypeChar_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PrototypeChar_AnimGraphNode_TransitionResult_A2323CD443EFC17F1EE06FBEAC6FCB54() end
---@param EntryPoint int32
function UABP_PrototypeChar_C:ExecuteUbergraph_ABP_PrototypeChar(EntryPoint) end


