---@meta

---@class UBPFamilyInviteDialogWidget_C : UFamilyInviteDialogWidget
---@field BlackBG UImage
---@field BPFamilyInviteDialogPlayerListEntryWidget UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_1 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_2 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_3 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_4 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_5 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_6 UBPFamilyInviteDialogPlayerListEntryWidget_C
---@field BPFamilyInviteDialogPlayerListEntryWidget_7 UBPFamilyInviteDialogPlayerListEntryWidget_C
UBPFamilyInviteDialogWidget_C = {}



