---@meta

---@class ABPVisCentralMarketplace_C : AVisCentralMarketplace
---@field VisStaticMesh10 UVisStaticMeshComponent
---@field VisStaticMesh9 UVisStaticMeshComponent
---@field VisStaticMesh20 UVisStaticMeshComponent
---@field VisStaticMesh27 UVisStaticMeshComponent
---@field VisStaticMesh18 UVisStaticMeshComponent
---@field VisStaticMesh34 UVisStaticMeshComponent
---@field Pickaxe UVisStaticMeshComponent
---@field Bow UVisStaticMeshComponent
---@field VisStaticMesh26 UVisStaticMeshComponent
---@field VisStaticMesh25 UVisStaticMeshComponent
---@field PropsMeshes UVisStaticMeshComponent
---@field PropsMeshes1 UVisStaticMeshComponent
---@field VisStaticMesh24 UVisStaticMeshComponent
---@field VisStaticMesh32 UVisStaticMeshComponent
---@field VisStaticMesh30 UVisStaticMeshComponent
---@field Boxes UVisStaticMeshComponent
---@field VisStaticMesh28 UVisStaticMeshComponent
---@field VisStaticMesh23 UVisStaticMeshComponent
---@field VisStaticMesh22 UVisStaticMeshComponent
---@field VisStaticMesh12 UVisStaticMeshComponent
---@field VisStaticMesh3 UVisStaticMeshComponent
---@field VisStaticMesh13 UVisStaticMeshComponent
---@field VisStaticMesh11 UVisStaticMeshComponent
---@field VisStaticMesh4 UVisStaticMeshComponent
---@field WeapoNRack UVisStaticMeshComponent
---@field VisStaticMesh5 UVisStaticMeshComponent
---@field VisStaticMesh7 UVisStaticMeshComponent
---@field VisStaticMesh19 UVisStaticMeshComponent
---@field VisStaticMesh17 UVisStaticMeshComponent
---@field Decal UDecalComponent
---@field Decal1 UDecalComponent
---@field VisStaticMesh16 UVisStaticMeshComponent
---@field VisStaticMesh15 UVisStaticMeshComponent
---@field VisStaticMesh14 UVisStaticMeshComponent
---@field Cart UVisStaticMeshComponent
---@field VisStaticMesh8 UVisStaticMeshComponent
---@field VisStaticMesh6 UVisStaticMeshComponent
---@field BigBoxes UVisStaticMeshComponent
---@field BPVisFamilyMeshComponent UBPVisFamilyMeshComponent_C
---@field Fire USceneComponent
---@field Structure UVisStaticMeshComponent
---@field ScorchEffect5 UScorchEffectComponent
---@field ScorchEffect4 UScorchEffectComponent
---@field ScorchEffect1 UScorchEffectComponent
---@field ScorchEffect7 UScorchEffectComponent
---@field ScorchEffect8 UScorchEffectComponent
---@field ScorchEffect6 UScorchEffectComponent
ABPVisCentralMarketplace_C = {}



