---@meta

---@class ABPVisGridFoundationRoundStraight_T2_C : AVisStructure
---@field Rubble UVisStaticMeshComponentBase
---@field TopMeshCollapsed UVisStaticMeshComponentBase
---@field VisDynamicMeshTemplateReference2 UVisDynamicMeshTemplateReferenceComponent
---@field VisDynamicMeshTemplateReference3 UVisDynamicMeshTemplateReferenceComponent
---@field VisDynamicMeshTemplateReference1 UVisDynamicMeshTemplateReferenceComponent
---@field VisDynamicMeshTemplateReference UVisDynamicMeshTemplateReferenceComponent
---@field VisDynamicInstancedMeshGroup UVisDynamicInstancedMeshGroupComponent
---@field FloorPlanking2 UStaticMeshComponent
---@field FloorPlanking UStaticMeshComponent
---@field VisFoundationEdgeMeshDecor UVisFoundationEdgeMeshDecorComponent
---@field VisFoundationEdgeMeshDecor6 UVisFoundationEdgeMeshDecorComponent
---@field VisFoundationEdgeMeshDecor1 UVisFoundationEdgeMeshDecorComponent
---@field VisFoundationEdgeMeshDecor2 UVisFoundationEdgeMeshDecorComponent
---@field VisFoundationEdgeMeshDecor5 UVisFoundationEdgeMeshDecorComponent
---@field VisFoundationEdgeMeshDecor4 UVisFoundationEdgeMeshDecorComponent
---@field TopMesh UStaticMeshComponent
---@field BottomMesh UVisFoundationBottomMeshDecorComponent
---@field VisRandomMeshDecor UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor13 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor33 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor22 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor32 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor14 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor34 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor29 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor8 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor19 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor11 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor7 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor24 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor16 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor9 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor26 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor31 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor17 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor18 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor15 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor27 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor12 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor23 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor21 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor5 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor6 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor10 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor25 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor20 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor30 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor28 UVisRandomMeshDecorComponent
---@field Scene USceneComponent
local ABPVisGridFoundationRoundStraight_T2_C = {}



