---@meta

---@class AFaceBrickTemplate1200BaseDiagonaltT2_C : AActor
---@field VisRandomMeshDecor63 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor62 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor61 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor60 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor59 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor58 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor57 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor56 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor55 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor54 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor53 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor52 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor51 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor50 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor49 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor48 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor47 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor46 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor45 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor44 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor43 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor42 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor1 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor41 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor40 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor39 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor38 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor37 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor36 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor35 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor30 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor27 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor28 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor11 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor29 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor26 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor25 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor24 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor32 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor31 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor22 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor14 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor34 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor33 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor21 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor7 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor9 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor8 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor10 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor6 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor5 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor23 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor17 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor19 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor18 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor12 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor15 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor16 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor20 UVisRandomMeshDecorComponent
---@field VisRandomMeshDecor13 UVisRandomMeshDecorComponent
local AFaceBrickTemplate1200BaseDiagonaltT2_C = {}



